[user@latitude5400 project]$ python test_phase1_core.py 
F..F..FFFFFFFFFFFFFF...FFF.FFFFFFFFFFFFF.FFFFF.F...F.F.F..FFF..
======================================================================
FAIL: test_add (__main__.TestEval.test_add)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 44, in test_add
    self.expect(expr, 136)
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Add object at 0x711653f747d0>) threw TypeError (should be 136)

======================================================================
FAIL: test_and (__main__.TestEval.test_and)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 134, in test_and
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.And object at 0x711654275950>) threw TypeError (should be True)

======================================================================
FAIL: test_and_short_circuit_error (__main__.TestEval.test_and_short_circuit_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 164, in test_and_short_circuit_error
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.And object at 0x711653f78510>) threw TypeError (should be False)

======================================================================
FAIL: test_and_short_circuit_type_error (__main__.TestEval.test_and_short_circuit_type_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 170, in test_and_short_circuit_type_error
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.And object at 0x711653f33530>) threw TypeError (should be False)

======================================================================
FAIL: test_complex_1 (__main__.TestEval.test_complex_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 382, in test_complex_1
    self.expect(expr, -1389)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Add object at 0x711653f33770>) threw TypeError (should be -1389)

======================================================================
FAIL: test_complex_10 (__main__.TestEval.test_complex_10)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 464, in test_complex_10
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711653f788a0>) threw TypeError (should be True)

======================================================================
FAIL: test_complex_11 (__main__.TestEval.test_complex_11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 476, in test_complex_11
    self.expect(expr, -687)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Add object at 0x711653f03570>) threw TypeError (should be -687)

======================================================================
FAIL: test_complex_2 (__main__.TestEval.test_complex_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 388, in test_complex_2
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.And object at 0x711653f03bd0>) threw TypeError (should be True)

======================================================================
FAIL: test_complex_3 (__main__.TestEval.test_complex_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 394, in test_complex_3
    self.expect(expr, 26)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711653f90160>) threw TypeError (should be 26)

======================================================================
FAIL: test_complex_4 (__main__.TestEval.test_complex_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 402, in test_complex_4
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711653f906b0>) threw TypeError (should be False)

======================================================================
FAIL: test_complex_5 (__main__.TestEval.test_complex_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 411, in test_complex_5
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Or object at 0x711653f78fc0>) threw TypeError (should be True)

======================================================================
FAIL: test_complex_6 (__main__.TestEval.test_complex_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 424, in test_complex_6
    self.expect(expr, 106)
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711653eee550>) threw TypeError (should be 106)

======================================================================
FAIL: test_complex_7 (__main__.TestEval.test_complex_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 434, in test_complex_7
    self.expect(expr, 41)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711653f1b5c0>) threw TypeError (should be 41)

======================================================================
FAIL: test_complex_8 (__main__.TestEval.test_complex_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 444, in test_complex_8
    self.expect(expr, 72)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711653f982f0>) threw TypeError (should be 72)

======================================================================
FAIL: test_complex_9 (__main__.TestEval.test_complex_9)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 454, in test_complex_9
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711653f98590>) threw TypeError (should be True)

======================================================================
FAIL: test_div (__main__.TestEval.test_div)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 98, in test_div
    self.expect(expr, -3)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Div object at 0x711653f75310>) threw TypeError (should be -3)

======================================================================
FAIL: test_eq_bool (__main__.TestEval.test_eq_bool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 294, in test_eq_bool
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Eq object at 0x711653eeea50>) threw TypeError (should be True)

======================================================================
FAIL: test_eq_int (__main__.TestEval.test_eq_int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 284, in test_eq_int
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Eq object at 0x711653eeeb50>) threw TypeError (should be True)

======================================================================
FAIL: test_eq_type_mismatch (__main__.TestEval.test_eq_type_mismatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 312, in test_eq_type_mismatch
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Eq object at 0x711653f1be30>) threw TypeError (should be False)

======================================================================
FAIL: test_if_diff_branch_types (__main__.TestEval.test_if_diff_branch_types)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 376, in test_if_diff_branch_types
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711654157dd0>) threw TypeError (should be False)

======================================================================
FAIL: test_if_false (__main__.TestEval.test_if_false)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 352, in test_if_false
    self.expect(expr, -22)
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x711654157c50>) threw TypeError (should be -22)

======================================================================
FAIL: test_if_fbranch_error (__main__.TestEval.test_if_fbranch_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 364, in test_if_fbranch_error
    self.expect(expr, -39)
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x71165408e8e0>) threw TypeError (should be -39)

======================================================================
FAIL: test_if_tbranch_error (__main__.TestEval.test_if_tbranch_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 370, in test_if_tbranch_error
    self.expect(expr, 83)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x71165408e780>) threw TypeError (should be 83)

======================================================================
FAIL: test_if_true (__main__.TestEval.test_if_true)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 346, in test_if_true
    self.expect(expr, 64)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.If object at 0x71165429b390>) threw TypeError (should be 64)

======================================================================
FAIL: test_let (__main__.TestEval.test_let)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 237, in test_let
    self.expect(expr, 2)
    ~~~~~~~~~~~^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x711653f79480>) threw TypeError (should be 2)

======================================================================
FAIL: test_let_1 (__main__.TestEval.test_let_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 488, in test_let_1
    self.expect(expr, 42)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x711653f796e0>) threw TypeError (should be 42)

======================================================================
FAIL: test_let_2 (__main__.TestEval.test_let_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 504, in test_let_2
    self.expect(expr, 42)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x711653f9dbf0>) threw TypeError (should be 42)

======================================================================
FAIL: test_let_3 (__main__.TestEval.test_let_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 522, in test_let_3
    self.expect(expr, 42)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Add object at 0x71165408e990>) threw TypeError (should be 42)

======================================================================
FAIL: test_let_4 (__main__.TestEval.test_let_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 535, in test_let_4
    self.expect(expr, 42)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x711653fa0b90>) threw TypeError (should be 42)

======================================================================
FAIL: test_let_5 (__main__.TestEval.test_let_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 551, in test_let_5
    self.expect(expr, 42)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x71165404fd90>) threw TypeError (should be 42)

======================================================================
FAIL: test_let_6 (__main__.TestEval.test_let_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 567, in test_let_6
    self.expect(expr, 42)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x7116543eaa90>) threw TypeError (should be 42)

======================================================================
FAIL: test_lets (__main__.TestEval.test_lets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 257, in test_lets
    self.expect(expr, 1)
    ~~~~~~~~~~~^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x711654157dd0>) threw TypeError (should be 1)

======================================================================
FAIL: test_lets_shadowed (__main__.TestEval.test_lets_shadowed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 278, in test_lets_shadowed
    self.expect(expr,False)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Let object at 0x711653f6ba70>) threw TypeError (should be False)

======================================================================
FAIL: test_lit_false (__main__.TestEval.test_lit_false)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 32, in test_lit_false
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Lit object at 0x711653f673b0>) threw TypeError (should be False)

======================================================================
FAIL: test_lit_int (__main__.TestEval.test_lit_int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 38, in test_lit_int
    self.expect(expr, 11)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Lit object at 0x711653f67410>) threw TypeError (should be 11)

======================================================================
FAIL: test_lit_true (__main__.TestEval.test_lit_true)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 26, in test_lit_true
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Lit object at 0x711653f67170>) threw TypeError (should be False)

======================================================================
FAIL: test_lt (__main__.TestEval.test_lt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 322, in test_lt
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Lt object at 0x711653eeee50>) threw TypeError (should be True)

======================================================================
FAIL: test_mul (__main__.TestEval.test_mul)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 80, in test_mul
    self.expect(expr, 2482)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Mul object at 0x711653f332f0>) threw TypeError (should be 2482)

======================================================================
FAIL: test_neg (__main__.TestEval.test_neg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 122, in test_neg
    self.expect(expr, -13)
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Neg object at 0x711654023750>) threw TypeError (should be -13)

======================================================================
FAIL: test_not (__main__.TestEval.test_not)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 218, in test_not
    self.expect(expr, False)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Not object at 0x711654033820>) threw TypeError (should be False)

======================================================================
FAIL: test_or (__main__.TestEval.test_or)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 176, in test_or
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Or object at 0x711653f9e360>) threw TypeError (should be True)

======================================================================
FAIL: test_or_short_circuit_error (__main__.TestEval.test_or_short_circuit_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 206, in test_or_short_circuit_error
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Or object at 0x711653eeef50>) threw TypeError (should be True)

======================================================================
FAIL: test_or_short_circuit_type_error (__main__.TestEval.test_or_short_circuit_type_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 212, in test_or_short_circuit_type_error
    self.expect(expr, True)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Or object at 0x711653f1b110>) threw TypeError (should be True)

======================================================================
FAIL: test_sub (__main__.TestEval.test_sub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 13, in expect
    got = interp.eval(expr)
TypeError: eval() missing 1 required positional argument: 'env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CS358/project/test_phase1_core.py", line 62, in test_sub
    self.expect(expr, 42)
    ~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/CS358/project/test_phase1_core.py", line 15, in expect
    self.fail(f"eval({expr}) threw {type(e).__name__} (should be {expected})")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: eval(<interp.Sub object at 0x711654033950>) threw TypeError (should be 42)

----------------------------------------------------------------------
Ran 63 tests in 0.054s

FAILED (failures=44)